### PR TITLE
nix: add desktop item and fix names

### PR DESCRIPTION
**Pull request by ein-shved**
Add .desktop file to Nix package to make it true application.

Fix names to be more nix-way: dashes (-) instead of underscore (_)

### CODE REVIEW

**Review by cucumber-sp — CHANGES_REQUESTED** [review]
You should put all NixOS files to specific folder I think

**Review by cucumber-sp — CHANGES_REQUESTED** [review]
You should put all NixOS files to specific folder I think

**Comment by ein-shved** [comment]
> You should put all NixOS files to specific folder I think

Agree, but it is better to put `flake.nix` and `flake.lock` files to the root. Will you accept this?

**Comment by cucumber-sp** [comment]
> > You should put all NixOS files to specific folder I think
> 
> Agree, but it is better to put `flake.nix` and `flake.lock` files to the root. Will you accept this?

works for me

**Pull request merged**
